(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "ag")
(depends-on "idle-highlight-mode")
(depends-on "ruby-mode")
(depends-on "ruby-tools")
(depends-on "ruby-end")
(depends-on "rvm")
(depends-on "css-mode")
(depends-on "scss-mode")
(depends-on "yaml-mode")
(depends-on "haml-mode")
(depends-on "magit")
(depends-on "gist")
(depends-on "coffee-mode")
(depends-on "flycheck")
(depends-on "yasnippet")
(depends-on "nginx-mode")
(depends-on "volatile-highlights")
(depends-on "guru-mode")
(depends-on "go-mode")
(depends-on "go-play")
(depends-on "go-snippets")
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "grizzl")
(depends-on "markdown-mode")
(depends-on "google-c-style")
(depends-on "handlebars-sgml-mode")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "lusty-explorer")           ; epic ido replacement
(depends-on "expand-region")
(depends-on "smart-mode-line")
(depends-on "smartparens")
;; Local Variables:
;; mode: emacs-lisp
;; End:
