(source gnu)
(source melpa)

(depends-on "ag")
(depends-on "idle-highlight-mode")
(depends-on "ruby-mode")
(depends-on "ruby-tools")
(depends-on "ruby-end")
(depends-on "rvm")
(depends-on "css-mode")
(depends-on "scss-mode")
(depends-on "yaml-mode")
(depends-on "haml-mode")
(depends-on "magit")
(depends-on "gist")
(depends-on "coffee-mode")
(depends-on "flycheck")
(depends-on "yasnippet")
(depends-on "volatile-highlights")
(depends-on "guru-mode")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "projectile")
(depends-on "grizzl")
(depends-on "markdown-mode")
(depends-on "google-c-style")
(depends-on "handlebars-sgml-mode")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "moe-theme")
(depends-on "expand-region")
(depends-on "smartparens")
(depends-on "neotree")
(depends-on "powerline")

;; Local Variables:
;; mode: emacs-lisp
;; End:
